version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16
    

    working_directory: ~/client

    steps:
      - add_ssh_keys:
          fingerprints:
            - "be:ab:18:5c:df:da:f4:2b:c9:54:da:02:f6:b0:ba:17"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

workflows:
  version: 2
  test:
    jobs:
      - build